// AUTO-GENERATED by scripts/gen_country_shapes.py from Natural Earth 1:110m
// admin-0 countries (public domain / CC0). DO NOT EDIT BY HAND — edit the
// script's PLACE_COUNTRY map / tolerances and regenerate.
package com.acme.clara.data

import androidx.compose.ui.geometry.Offset

/**
 * Passport (C4) country silhouettes, projected through the same Mercator transform
 * as [Expansion.project]/[WorldMap] so they overlay the raster DEPART map. Each
 * country is a list of filled rings (islands); coords are normalised 0..1 in the
 * map interior. Codes in [dotFallback] have no usable 110m polygon (micro-states,
 * Antarctica) and are stamped at the visited place's map dot instead.
 */
object CountryShapes {
    /** Every game place -> its ADM0_A3 country code. */
    val placeCountry: Map<String, String> = mapOf(
        "Abu Simbel" to "EGY",
        "Afghanistan" to "AFG",
        "Albania" to "ALB",
        "Algeria" to "DZA",
        "Amsterdam" to "NLD",
        "Andorra" to "AND",
        "Angola" to "AGO",
        "Antarctica" to "ATA",
        "Antigua and Barbuda" to "ATG",
        "Armenia" to "ARM",
        "Athens" to "GRC",
        "Azerbaijan" to "AZE",
        "Baghdad" to "IRQ",
        "Bahamas" to "BHS",
        "Bahrain" to "BHR",
        "Bali" to "IDN",
        "Bamako" to "MLI",
        "Bangkok" to "THA",
        "Bangladesh" to "BGD",
        "Barbados" to "BRB",
        "Beijing" to "CHN",
        "Belarus" to "BLR",
        "Belgium" to "BEL",
        "Belize" to "BLZ",
        "Benin" to "BEN",
        "Berlin" to "DEU",
        "Bhutan" to "BTN",
        "Bosnia and Herzegovina" to "BIH",
        "Botswana" to "BWA",
        "Brunei" to "BRN",
        "Budapest" to "HUN",
        "Buenos Aires" to "ARG",
        "Bulgaria" to "BGR",
        "Burkina Faso" to "BFA",
        "Burundi" to "BDI",
        "Cabo Verde" to "CPV",
        "Cairo" to "EGY",
        "Cambodia" to "KHM",
        "Cameroon" to "CMR",
        "Cape Town" to "ZAF",
        "Cappadocia" to "TUR",
        "Casablanca" to "MAR",
        "Central African Republic" to "CAF",
        "Chad" to "TCD",
        "Chichen Itza" to "MEX",
        "Cologne" to "DEU",
        "Colombia" to "COL",
        "Colombo" to "LKA",
        "Congo (Republic of the)" to "COG",
        "Copenhagen" to "DNK",
        "Costa Rica" to "CRI",
        "Cuba" to "CUB",
        "Cyprus" to "CYP",
        "Côte d'Ivoire" to "CIV",
        "DR Congo" to "COD",
        "Djibouti" to "DJI",
        "Dominica" to "DMA",
        "Dominican Republic" to "DOM",
        "Dubai" to "ARE",
        "Dubrovnik" to "HRV",
        "Easter Island" to "CHL",
        "Ecuador" to "ECU",
        "Edinburgh" to "GBR",
        "El Salvador" to "SLV",
        "Equatorial Guinea" to "GNQ",
        "Eritrea" to "ERI",
        "Estonia" to "EST",
        "Eswatini" to "SWZ",
        "Ethiopia" to "ETH",
        "Fiji" to "FJI",
        "Finland" to "FIN",
        "Gabon" to "GAB",
        "Gambia" to "GMB",
        "Georgia" to "GEO",
        "Ghana" to "GHA",
        "Grand Canyon" to "USA",
        "Greenland" to "GRL",
        "Grenada" to "GRD",
        "Guatemala" to "GTM",
        "Guinea" to "GIN",
        "Guinea-Bissau" to "GNB",
        "Gujarat" to "IND",
        "Guyana" to "GUY",
        "Ha Long Bay" to "VNM",
        "Haiti" to "HTI",
        "Honduras" to "HND",
        "Hong Kong" to "CHN",
        "Honolulu" to "USA",
        "Iguazu Falls" to "ARG",
        "Iran" to "IRN",
        "Ireland" to "IRL",
        "Istanbul" to "TUR",
        "Jamaica" to "JAM",
        "Jerusalem" to "ISR",
        "Jordan" to "JOR",
        "Kathmandu" to "NPL",
        "Kazakhstan" to "KAZ",
        "Kenya" to "KEN",
        "Kigali" to "RWA",
        "Kiribati" to "KIR",
        "Kosovo" to "KOS",
        "Krakow" to "POL",
        "Kuala Lumpur" to "MYS",
        "Kuwait" to "KWT",
        "Kyrgyzstan" to "KGZ",
        "Laos" to "LAO",
        "Las Vegas" to "USA",
        "Latvia" to "LVA",
        "Lebanon" to "LBN",
        "Lesotho" to "LSO",
        "Liberia" to "LBR",
        "Libya" to "LBY",
        "Liechtenstein" to "LIE",
        "Lima" to "PER",
        "Lisbon" to "PRT",
        "Lithuania" to "LTU",
        "London" to "GBR",
        "Los Angeles" to "USA",
        "Luxembourg" to "LUX",
        "Madagascar" to "MDG",
        "Malawi" to "MWI",
        "Maldives" to "MDV",
        "Malta" to "MLT",
        "Maranhao" to "BRA",
        "Marrakech" to "MAR",
        "Marshall Islands" to "MHL",
        "Mauritania" to "MRT",
        "Mauritius" to "MUS",
        "Mexico City" to "MEX",
        "Micronesia" to "FSM",
        "Moldova" to "MDA",
        "Monaco" to "MCO",
        "Mongolia" to "MNG",
        "Mont Saint-Michel" to "FRA",
        "Montenegro" to "MNE",
        "Montreal" to "CAN",
        "Moroni" to "COM",
        "Moscow" to "RUS",
        "Mount Everest" to "NPL",
        "Mount Rushmore" to "USA",
        "Mozambique" to "MOZ",
        "Myanmar" to "MMR",
        "Namibia" to "NAM",
        "Nauru" to "NRU",
        "Neuschwanstein" to "DEU",
        "New Delhi" to "IND",
        "New York" to "USA",
        "New Zealand" to "NZL",
        "Nicaragua" to "NIC",
        "Niger" to "NER",
        "Nigeria" to "NGA",
        "North Korea" to "PRK",
        "North Macedonia" to "MKD",
        "Northern Ireland" to "GBR",
        "Novosibirsk" to "RUS",
        "Oman" to "OMN",
        "Oslo" to "NOR",
        "Pakistan" to "PAK",
        "Palau" to "PLW",
        "Palestine" to "PSX",
        "Panama" to "PAN",
        "Paraguay" to "PRY",
        "Paris" to "FRA",
        "Philippines" to "PHL",
        "Pisa" to "ITA",
        "Pompeii" to "ITA",
        "Port Moresby" to "PNG",
        "Prague" to "CZE",
        "Qatar" to "QAT",
        "Reykjavik" to "ISL",
        "Rio de Janeiro" to "BRA",
        "Romania" to "ROU",
        "Rome" to "ITA",
        "Saint Kitts and Nevis" to "KNA",
        "Saint Lucia" to "LCA",
        "Saint Petersburg" to "RUS",
        "Saint Vincent and the Grenadines" to "VCT",
        "Salar de Uyuni" to "BOL",
        "Samarkand" to "UZB",
        "Samoa" to "WSM",
        "San Francisco" to "USA",
        "San Marino" to "SMR",
        "Santorini" to "GRC",
        "Sao Tome and Principe" to "STP",
        "Saudi Arabia" to "SAU",
        "Scottish Highlands" to "GBR",
        "Seattle" to "USA",
        "Senegal" to "SEN",
        "Serbia" to "SRB",
        "Seychelles" to "SYC",
        "Sierra Leone" to "SLE",
        "Singapore" to "SGP",
        "Slovakia" to "SVK",
        "Slovenia" to "SVN",
        "Solomon Islands" to "SLB",
        "Somalia" to "SOM",
        "South Korea" to "KOR",
        "South Sudan" to "SDS",
        "Stonehenge" to "GBR",
        "Sudan" to "SDN",
        "Suriname" to "SUR",
        "Svalbard" to "NOR",
        "Sweden" to "SWE",
        "Switzerland" to "CHE",
        "Sydney" to "AUS",
        "Syria" to "SYR",
        "Taipei" to "TWN",
        "Tajikistan" to "TJK",
        "Tanzania" to "TZA",
        "Timor-Leste" to "TLS",
        "Togo" to "TGO",
        "Tokyo" to "JPN",
        "Tonga" to "TON",
        "Toronto" to "CAN",
        "Trinidad and Tobago" to "TTO",
        "Tunisia" to "TUN",
        "Turkmenistan" to "TKM",
        "Tuvalu" to "TUV",
        "Uganda" to "UGA",
        "Ukraine" to "UKR",
        "Uruguay" to "URY",
        "Valencia" to "ESP",
        "Vanuatu" to "VUT",
        "Vatican City" to "VAT",
        "Venezuela" to "VEN",
        "Venice" to "ITA",
        "Vienna" to "AUT",
        "Washington DC" to "USA",
        "Yemen" to "YEM",
        "Zambia" to "ZMB",
        "Zimbabwe" to "ZWE",
    )

    /** Representative map position for every country destination in Expansion2. */
    val placePosition: Map<String, Offset> = mapOf(
        "Afghanistan" to Offset(0.6915f, 0.3402f),
        "Albania" to Offset(0.5541f, 0.2891f),
        "Algeria" to Offset(0.5028f, 0.3893f),
        "Andorra" to Offset(0.4992f, 0.2736f),
        "Angola" to Offset(0.5478f, 0.6438f),
        "Antigua and Barbuda" to Offset(0.3114f, 0.4592f),
        "Armenia" to Offset(0.6272f, 0.2907f),
        "Azerbaijan" to Offset(0.6344f, 0.2912f),
        "Bahamas" to Offset(0.2659f, 0.3963f),
        "Bahrain" to Offset(0.6443f, 0.3986f),
        "Bangladesh" to Offset(0.7602f, 0.4114f),
        "Barbados" to Offset(0.3181f, 0.4842f),
        "Belarus" to Offset(0.5787f, 0.1672f),
        "Belgium" to Offset(0.5087f, 0.1982f),
        "Belize" to Offset(0.2317f, 0.4582f),
        "Benin" to Offset(0.5015f, 0.5024f),
        "Bosnia and Herzegovina" to Offset(0.5480f, 0.2601f),
        "Botswana" to Offset(0.5661f, 0.7087f),
        "Brunei" to Offset(0.8339f, 0.5394f),
        "Bulgaria" to Offset(0.5690f, 0.2737f),
        "Burkina Faso" to Offset(0.4904f, 0.4875f),
        "Burundi" to Offset(0.5831f, 0.5880f),
        "Cabo Verde" to Offset(0.4245f, 0.4717f),
        "Cameroon" to Offset(0.5314f, 0.5386f),
        "Central African Republic" to Offset(0.5564f, 0.5235f),
        "Chad" to Offset(0.5497f, 0.4716f),
        "Colombia" to Offset(0.2777f, 0.5461f),
        "Congo (Republic of the)" to Offset(0.5416f, 0.5663f),
        "Costa Rica" to Offset(0.2454f, 0.5041f),
        "Cuba" to Offset(0.2635f, 0.4309f),
        "Cyprus" to Offset(0.5925f, 0.3345f),
        "Côte d'Ivoire" to Offset(0.4780f, 0.5203f),
        "DR Congo" to Offset(0.5640f, 0.5788f),
        "Djibouti" to Offset(0.6204f, 0.4919f),
        "Dominica" to Offset(0.3127f, 0.4698f),
        "Dominican Republic" to Offset(0.2852f, 0.4457f),
        "Ecuador" to Offset(0.2628f, 0.5751f),
        "El Salvador" to Offset(0.2311f, 0.4810f),
        "Equatorial Guinea" to Offset(0.5211f, 0.5526f),
        "Eritrea" to Offset(0.6079f, 0.4674f),
        "Estonia" to Offset(0.5711f, 0.1120f),
        "Eswatini" to Offset(0.5877f, 0.7390f),
        "Ethiopia" to Offset(0.6103f, 0.5169f),
        "Fiji" to Offset(1.0000f, 0.6803f),
        "Finland" to Offset(0.5753f, 0.0537f),
        "Gabon" to Offset(0.5296f, 0.5699f),
        "Gambia" to Offset(0.4501f, 0.4813f),
        "Georgia" to Offset(0.6241f, 0.2790f),
        "Ghana" to Offset(0.4914f, 0.5189f),
        "Grenada" to Offset(0.3118f, 0.4910f),
        "Guatemala" to Offset(0.2264f, 0.4726f),
        "Guinea" to Offset(0.4648f, 0.5006f),
        "Guinea-Bissau" to Offset(0.4515f, 0.4907f),
        "Guyana" to Offset(0.3199f, 0.5352f),
        "Haiti" to Offset(0.2805f, 0.4447f),
        "Honduras" to Offset(0.2371f, 0.4738f),
        "Iran" to Offset(0.6572f, 0.3551f),
        "Jamaica" to Offset(0.2654f, 0.4521f),
        "Kazakhstan" to Offset(0.6980f, 0.2150f),
        "Kiribati" to Offset(0.0283f, 0.5555f),
        "Kosovo" to Offset(0.5563f, 0.2729f),
        "Kuwait" to Offset(0.6347f, 0.3750f),
        "Kyrgyzstan" to Offset(0.7153f, 0.2807f),
        "Laos" to Offset(0.7983f, 0.4436f),
        "Latvia" to Offset(0.5699f, 0.1315f),
        "Lebanon" to Offset(0.6011f, 0.3404f),
        "Lesotho" to Offset(0.5782f, 0.7598f),
        "Liberia" to Offset(0.4665f, 0.5269f),
        "Libya" to Offset(0.5479f, 0.3947f),
        "Liechtenstein" to Offset(0.5228f, 0.2329f),
        "Lithuania" to Offset(0.5659f, 0.1535f),
        "Luxembourg" to Offset(0.5125f, 0.2085f),
        "Madagascar" to Offset(0.6329f, 0.6855f),
        "Malawi" to Offset(0.5941f, 0.6515f),
        "Maldives" to Offset(0.7114f, 0.5472f),
        "Malta" to Offset(0.5373f, 0.3269f),
        "Marshall Islands" to Offset(1.0000f, 0.5226f),
        "Mauritania" to Offset(0.4656f, 0.4425f),
        "Micronesia" to Offset(0.9632f, 0.5239f),
        "Moldova" to Offset(0.5789f, 0.2302f),
        "Montenegro" to Offset(0.5512f, 0.2712f),
        "Mozambique" to Offset(0.6066f, 0.6551f),
        "Namibia" to Offset(0.5452f, 0.6984f),
        "Nauru" to Offset(0.9891f, 0.5704f),
        "New Zealand" to Offset(1.0000f, 0.8380f),
        "Nicaragua" to Offset(0.2425f, 0.4875f),
        "Niger" to Offset(0.5226f, 0.4566f),
        "Nigeria" to Offset(0.5167f, 0.5080f),
        "North Korea" to Offset(0.8691f, 0.2954f),
        "North Macedonia" to Offset(0.5584f, 0.2816f),
        "Oman" to Offset(0.6644f, 0.4256f),
        "Pakistan" to Offset(0.6976f, 0.3757f),
        "Palestine" to Offset(0.5990f, 0.3559f),
        "Panama" to Offset(0.2564f, 0.5126f),
        "Paraguay" to Offset(0.3163f, 0.7058f),
        "Qatar" to Offset(0.6460f, 0.4044f),
        "Romania" to Offset(0.5685f, 0.2456f),
        "Saint Kitts and Nevis" to Offset(0.3085f, 0.4572f),
        "Saint Lucia" to Offset(0.3138f, 0.4795f),
        "Saint Vincent and the Grenadines" to Offset(0.3132f, 0.4838f),
        "Samoa" to Offset(0.0000f, 0.6539f),
        "Sao Tome and Principe" to Offset(0.5141f, 0.5660f),
        "Saudi Arabia" to Offset(0.6269f, 0.4142f),
        "Senegal" to Offset(0.4507f, 0.4716f),
        "Serbia" to Offset(0.5561f, 0.2592f),
        "Seychelles" to Offset(0.6589f, 0.5964f),
        "Sierra Leone" to Offset(0.4596f, 0.5132f),
        "Slovakia" to Offset(0.5509f, 0.2180f),
        "Slovenia" to Offset(0.5387f, 0.2427f),
        "Solomon Islands" to Offset(0.9661f, 0.6175f),
        "Somalia" to Offset(0.6284f, 0.5449f),
        "South Korea" to Offset(0.8741f, 0.3232f),
        "South Sudan" to Offset(0.5845f, 0.5220f),
        "Sudan" to Offset(0.5812f, 0.4639f),
        "Suriname" to Offset(0.3288f, 0.5413f),
        "Sweden" to Offset(0.5508f, 0.0158f),
        "Switzerland" to Offset(0.5166f, 0.2367f),
        "Syria" to Offset(0.6079f, 0.3338f),
        "Tajikistan" to Offset(0.7095f, 0.3089f),
        "Tanzania" to Offset(0.5981f, 0.6050f),
        "Timor-Leste" to Offset(0.8674f, 0.6223f),
        "Togo" to Offset(0.4976f, 0.5120f),
        "Tonga" to Offset(0.0000f, 0.7025f),
        "Trinidad and Tobago" to Offset(0.3140f, 0.4982f),
        "Tunisia" to Offset(0.5212f, 0.3437f),
        "Uganda" to Offset(0.5921f, 0.5549f),
        "Ukraine" to Offset(0.5897f, 0.2086f),
        "Uruguay" to Offset(0.3287f, 0.7852f),
        "Vanuatu" to Offset(0.9890f, 0.6643f),
        "Venezuela" to Offset(0.3031f, 0.5223f),
        "Yemen" to Offset(0.6304f, 0.4704f),
        "Zambia" to Offset(0.5727f, 0.6597f),
        "Zimbabwe" to Offset(0.5832f, 0.6874f),
    )

    /** ADM0_A3 -> display name. */
    val countryName: Map<String, String> = mapOf(
        "AFG" to "Afghanistan",
        "AGO" to "Angola",
        "ALB" to "Albania",
        "AND" to "Andorra",
        "ARE" to "United Arab Emirates",
        "ARG" to "Argentina",
        "ARM" to "Armenia",
        "ATA" to "Antarctica",
        "ATG" to "Antigua and Barbuda",
        "AUS" to "Australia",
        "AUT" to "Austria",
        "AZE" to "Azerbaijan",
        "BDI" to "Burundi",
        "BEL" to "Belgium",
        "BEN" to "Benin",
        "BFA" to "Burkina Faso",
        "BGD" to "Bangladesh",
        "BGR" to "Bulgaria",
        "BHR" to "Bahrain",
        "BHS" to "Bahamas",
        "BIH" to "Bosnia and Herz.",
        "BLR" to "Belarus",
        "BLZ" to "Belize",
        "BOL" to "Bolivia",
        "BRA" to "Brazil",
        "BRB" to "Barbados",
        "BRN" to "Brunei",
        "BTN" to "Bhutan",
        "BWA" to "Botswana",
        "CAF" to "Central African Rep.",
        "CAN" to "Canada",
        "CHE" to "Switzerland",
        "CHL" to "Chile",
        "CHN" to "China",
        "CIV" to "Côte d'Ivoire",
        "CMR" to "Cameroon",
        "COD" to "Dem. Rep. Congo",
        "COG" to "Congo",
        "COL" to "Colombia",
        "COM" to "COM",
        "CPV" to "Cabo Verde",
        "CRI" to "Costa Rica",
        "CUB" to "Cuba",
        "CYP" to "Cyprus",
        "CZE" to "Czechia",
        "DEU" to "Germany",
        "DJI" to "Djibouti",
        "DMA" to "Dominica",
        "DNK" to "Denmark",
        "DOM" to "Dominican Rep.",
        "DZA" to "Algeria",
        "ECU" to "Ecuador",
        "EGY" to "Egypt",
        "ERI" to "Eritrea",
        "ESP" to "Spain",
        "EST" to "Estonia",
        "ETH" to "Ethiopia",
        "FIN" to "Finland",
        "FJI" to "Fiji",
        "FRA" to "France",
        "FSM" to "Micronesia",
        "GAB" to "Gabon",
        "GBR" to "United Kingdom",
        "GEO" to "Georgia",
        "GHA" to "Ghana",
        "GIN" to "Guinea",
        "GMB" to "Gambia",
        "GNB" to "Guinea-Bissau",
        "GNQ" to "Eq. Guinea",
        "GRC" to "Greece",
        "GRD" to "Grenada",
        "GRL" to "Greenland",
        "GTM" to "Guatemala",
        "GUY" to "Guyana",
        "HND" to "Honduras",
        "HRV" to "Croatia",
        "HTI" to "Haiti",
        "HUN" to "Hungary",
        "IDN" to "Indonesia",
        "IND" to "India",
        "IRL" to "Ireland",
        "IRN" to "Iran",
        "IRQ" to "Iraq",
        "ISL" to "Iceland",
        "ISR" to "Israel",
        "ITA" to "Italy",
        "JAM" to "Jamaica",
        "JOR" to "Jordan",
        "JPN" to "Japan",
        "KAZ" to "Kazakhstan",
        "KEN" to "Kenya",
        "KGZ" to "Kyrgyzstan",
        "KHM" to "Cambodia",
        "KIR" to "Kiribati",
        "KNA" to "Saint Kitts and Nevis",
        "KOR" to "South Korea",
        "KOS" to "Kosovo",
        "KWT" to "Kuwait",
        "LAO" to "Laos",
        "LBN" to "Lebanon",
        "LBR" to "Liberia",
        "LBY" to "Libya",
        "LCA" to "Saint Lucia",
        "LIE" to "Liechtenstein",
        "LKA" to "Sri Lanka",
        "LSO" to "Lesotho",
        "LTU" to "Lithuania",
        "LUX" to "Luxembourg",
        "LVA" to "Latvia",
        "MAR" to "Morocco",
        "MCO" to "MCO",
        "MDA" to "Moldova",
        "MDG" to "Madagascar",
        "MDV" to "Maldives",
        "MEX" to "Mexico",
        "MHL" to "Marshall Islands",
        "MKD" to "North Macedonia",
        "MLI" to "Mali",
        "MLT" to "Malta",
        "MMR" to "Myanmar",
        "MNE" to "Montenegro",
        "MNG" to "Mongolia",
        "MOZ" to "Mozambique",
        "MRT" to "Mauritania",
        "MUS" to "MUS",
        "MWI" to "Malawi",
        "MYS" to "Malaysia",
        "NAM" to "Namibia",
        "NER" to "Niger",
        "NGA" to "Nigeria",
        "NIC" to "Nicaragua",
        "NLD" to "Netherlands",
        "NOR" to "Norway",
        "NPL" to "Nepal",
        "NRU" to "Nauru",
        "NZL" to "New Zealand",
        "OMN" to "Oman",
        "PAK" to "Pakistan",
        "PAN" to "Panama",
        "PER" to "Peru",
        "PHL" to "Philippines",
        "PLW" to "PLW",
        "PNG" to "Papua New Guinea",
        "POL" to "Poland",
        "PRK" to "North Korea",
        "PRT" to "Portugal",
        "PRY" to "Paraguay",
        "PSX" to "Palestine",
        "QAT" to "Qatar",
        "ROU" to "Romania",
        "RUS" to "Russia",
        "RWA" to "Rwanda",
        "SAU" to "Saudi Arabia",
        "SDN" to "Sudan",
        "SDS" to "S. Sudan",
        "SEN" to "Senegal",
        "SGP" to "SGP",
        "SLB" to "Solomon Is.",
        "SLE" to "Sierra Leone",
        "SLV" to "El Salvador",
        "SMR" to "SMR",
        "SOM" to "Somalia",
        "SRB" to "Serbia",
        "STP" to "Sao Tome and Principe",
        "SUR" to "Suriname",
        "SVK" to "Slovakia",
        "SVN" to "Slovenia",
        "SWE" to "Sweden",
        "SWZ" to "eSwatini",
        "SYC" to "Seychelles",
        "SYR" to "Syria",
        "TCD" to "Chad",
        "TGO" to "Togo",
        "THA" to "Thailand",
        "TJK" to "Tajikistan",
        "TKM" to "Turkmenistan",
        "TLS" to "Timor-Leste",
        "TON" to "Tonga",
        "TTO" to "Trinidad and Tobago",
        "TUN" to "Tunisia",
        "TUR" to "Turkey",
        "TUV" to "TUV",
        "TWN" to "Taiwan",
        "TZA" to "Tanzania",
        "UGA" to "Uganda",
        "UKR" to "Ukraine",
        "URY" to "Uruguay",
        "USA" to "United States of America",
        "UZB" to "Uzbekistan",
        "VAT" to "VAT",
        "VCT" to "Saint Vincent and the Grenadines",
        "VEN" to "Venezuela",
        "VNM" to "Vietnam",
        "VUT" to "Vanuatu",
        "WSM" to "Samoa",
        "YEM" to "Yemen",
        "ZAF" to "South Africa",
        "ZMB" to "Zambia",
        "ZWE" to "Zimbabwe",
    )

    /** Countries with no silhouette — stamp the visited place's dot instead. */
    val dotFallback: Set<String> = setOf("AND", "ARM", "ATA", "ATG", "BDI", "BHR", "BHS", "BLZ", "BRB", "BRN", "BTN", "COM", "CPV", "CYP", "DJI", "DMA", "FJI", "FSM", "GMB", "GNB", "GNQ", "GRD", "ISR", "JAM", "KIR", "KNA", "KOS", "KWT", "LBN", "LCA", "LIE", "LSO", "LUX", "MCO", "MDV", "MHL", "MKD", "MLT", "MNE", "MUS", "NRU", "PLW", "PSX", "QAT", "RWA", "SGP", "SLB", "SLV", "SMR", "STP", "SVK", "SVN", "SWZ", "SYC", "TGO", "TLS", "TON", "TTO", "TUV", "TWN", "VAT", "VCT", "VUT", "WSM")

    /** Whether this destination's Passport page is open at the current campaign rank. */
    fun isPlaceUnlocked(place: String, rankIndex: Int, entitled: Boolean): Boolean {
        val wave = Progression.wave[place] ?: return true
        return entitled && wave <= Progression.unlockedMaxWave(rankIndex)
    }

    /** Countries still frosted in the Passport. A free/unlocked destination in a shared
     * country opens that silhouette even if another landmark there belongs to a later wave. */
    fun lockedCountryCodes(rankIndex: Int, entitled: Boolean): Set<String> {
        val unlocked = placeCountry.entries.filter {
            isPlaceUnlocked(it.key, rankIndex, entitled)
        }.mapTo(hashSetOf()) { it.value }
        return placeCountry.values.toSet() - unlocked
    }

    // packed silhouettes: "x,y x,y;..." rings, decoded lazily into Offsets.
    private val packed: Map<String, String> = mapOf(
        "AFG" to
            "0.692,0.316 0.704,0.307 0.707,0.320 0.717,0.317 0.706,0.326 0.700,0.357 0.691,0.372 0.675,0.372 0.676,0.329 0.692,0.316",
        "AGO" to
            "0.531,0.605 0.559,0.613 0.560,0.637 0.566,0.638 0.566,0.648 0.559,0.648 0.563,0.678 0.529,0.677 0.535,0.638 0.531,0.605",
        "ALB" to
            "0.557,0.288 0.552,0.292 0.553,0.272 0.557,0.288",
        "ARE" to
            "0.647,0.411 0.662,0.407 0.657,0.423 0.647,0.411",
        "ARG" to
            "0.291,0.955 0.300,0.982 0.291,0.978 0.291,0.955;0.324,0.765 0.321,0.796 0.326,0.815 0.302,0.849 0.306,0.861 0.295,0.887 0.300,0.902 0.290,0.936 0.293,0.952 0.281,0.948 0.277,0.922 0.283,0.880 0.281,0.859 0.292,0.725 0.298,0.707 0.308,0.708 0.323,0.729 0.321,0.743 0.336,0.736 0.324,0.765",
        "AUS" to
            "0.932,0.847 0.933,0.867 0.927,0.870 0.923,0.846 0.932,0.847;0.868,0.780 0.844,0.801 0.835,0.794 0.831,0.711 0.853,0.693 0.867,0.657 0.879,0.662 0.887,0.637 0.899,0.642 0.896,0.662 0.910,0.680 0.917,0.634 0.949,0.750 0.939,0.819 0.928,0.832 0.911,0.824 0.904,0.796 0.900,0.803 0.903,0.785 0.897,0.800 0.884,0.774 0.868,0.780",
        "AUT" to
            "0.545,0.224 0.538,0.239 0.523,0.233 0.533,0.230 0.535,0.217 0.545,0.224",
        "AZE" to
            "0.632,0.279 0.644,0.292 0.639,0.308 0.637,0.298 0.632,0.304 0.628,0.284 0.632,0.279",
        "BEL" to
            "0.513,0.198 0.511,0.210 0.502,0.195 0.513,0.198",
        "BEN" to
            "0.502,0.528 0.497,0.502 0.503,0.490 0.502,0.528",
        "BFA" to
            "0.478,0.502 0.491,0.473 0.501,0.488 0.486,0.507 0.478,0.502",
        "BGD" to
            "0.769,0.426 0.768,0.435 0.765,0.421 0.758,0.426 0.757,0.396 0.768,0.406 0.765,0.416 0.769,0.426",
        "BGR" to
            "0.562,0.259 0.579,0.263 0.577,0.278 0.562,0.283 0.562,0.259",
        "BIH" to
            "0.549,0.272 0.542,0.250 0.552,0.253 0.549,0.272",
        "BLR" to
            "0.578,0.142 0.586,0.149 0.591,0.172 0.587,0.175 0.589,0.185 0.564,0.190 0.564,0.166 0.578,0.142",
        "BOL" to
            "0.288,0.636 0.301,0.628 0.301,0.640 0.322,0.670 0.323,0.694 0.311,0.692 0.309,0.710 0.294,0.714 0.288,0.636",
        "BRA" to
            "0.336,0.791 0.324,0.765 0.336,0.736 0.329,0.710 0.323,0.709 0.322,0.670 0.301,0.640 0.301,0.628 0.287,0.637 0.278,0.627 0.279,0.600 0.287,0.594 0.288,0.556 0.300,0.562 0.307,0.553 0.302,0.542 0.315,0.535 0.320,0.559 0.338,0.554 0.342,0.541 0.344,0.566 0.351,0.575 0.390,0.601 0.390,0.624 0.380,0.649 0.373,0.708 0.353,0.728 0.336,0.791",
        "BWA" to
            "0.582,0.709 0.559,0.740 0.553,0.727 0.556,0.683 0.569,0.680 0.582,0.709",
        "CAF" to
            "0.576,0.534 0.552,0.536 0.542,0.553 0.537,0.533 0.562,0.497 0.576,0.534",
        "CAN" to
            "0.131,0.216 0.117,0.198 0.108,0.162 0.109,0.145 0.093,0.099 0.087,0.110 0.077,0.093 0.077,0.000 0.254,0.000 0.240,0.005 0.236,0.032 0.218,0.070 0.214,0.109 0.221,0.131 0.251,0.153 0.258,0.194 0.262,0.180 0.258,0.158 0.268,0.138 0.262,0.111 0.265,0.098 0.263,0.066 0.276,0.065 0.288,0.083 0.289,0.109 0.294,0.118 0.303,0.092 0.311,0.140 0.329,0.173 0.325,0.192 0.298,0.204 0.284,0.236 0.302,0.213 0.303,0.241 0.315,0.234 0.314,0.250 0.299,0.264 0.304,0.250 0.296,0.251 0.289,0.230 0.283,0.252 0.250,0.281 0.250,0.249 0.233,0.222 0.214,0.212 0.131,0.216;0.330,0.193 0.326,0.208 0.336,0.213 0.337,0.237 0.319,0.229 0.330,0.193;0.246,0.027 0.257,0.047 0.236,0.050 0.240,0.018 0.246,0.027;0.261,0.000 0.311,0.000 0.305,0.029 0.293,0.010 0.303,0.052 0.302,0.062 0.291,0.047 0.298,0.072 0.273,0.033 0.262,0.035 0.264,0.024 0.275,0.022 0.279,0.000 0.227,0.000 0.261,0.000",
        "CHE" to
            "0.523,0.229 0.525,0.239 0.512,0.241 0.514,0.229 0.523,0.229",
        "CHL" to
            "0.291,0.955 0.291,0.978 0.296,0.979 0.293,0.987 0.273,0.957 0.284,0.970 0.291,0.955;0.288,0.679 0.296,0.715 0.286,0.773 0.288,0.794 0.281,0.859 0.283,0.880 0.277,0.922 0.281,0.948 0.291,0.951 0.283,0.968 0.272,0.951 0.270,0.916 0.275,0.900 0.270,0.897 0.279,0.860 0.274,0.867 0.288,0.679",
        "CHN" to
            "0.732,0.275 0.731,0.253 0.754,0.213 0.764,0.235 0.764,0.250 0.780,0.272 0.818,0.274 0.826,0.251 0.849,0.237 0.837,0.224 0.857,0.171 0.868,0.178 0.873,0.208 0.883,0.227 0.895,0.220 0.889,0.251 0.883,0.252 0.882,0.275 0.843,0.305 0.857,0.315 0.847,0.335 0.856,0.359 0.855,0.384 0.846,0.409 0.822,0.438 0.807,0.417 0.796,0.432 0.789,0.426 0.784,0.414 0.787,0.389 0.779,0.375 0.758,0.390 0.728,0.360 0.728,0.339 0.713,0.299 0.732,0.275",
        "CIV" to
            "0.471,0.503 0.486,0.507 0.486,0.536 0.472,0.540 0.471,0.503",
        "CMR" to
            "0.537,0.486 0.537,0.538 0.542,0.556 0.523,0.553 0.520,0.533 0.529,0.524 0.537,0.486",
        "COD" to
            "0.581,0.595 0.586,0.619 0.580,0.621 0.579,0.641 0.582,0.651 0.560,0.637 0.559,0.613 0.546,0.618 0.543,0.604 0.531,0.603 0.542,0.589 0.552,0.536 0.583,0.538 0.587,0.553 0.581,0.595",
        "COG" to
            "0.549,0.545 0.541,0.591 0.527,0.592 0.537,0.580 0.533,0.553 0.549,0.545",
        "COL" to
            "0.296,0.559 0.288,0.556 0.287,0.594 0.260,0.557 0.266,0.543 0.265,0.514 0.282,0.489 0.277,0.510 0.281,0.523 0.295,0.529 0.296,0.559",
        "CRI" to
            "0.250,0.507 0.249,0.516 0.240,0.499 0.250,0.507",
        "CUB" to
            "0.251,0.418 0.275,0.438 0.243,0.427 0.251,0.418",
        "CZE" to
            "0.539,0.195 0.550,0.211 0.537,0.220 0.532,0.210 0.539,0.195",
        "DEU" to
            "0.536,0.168 0.539,0.195 0.531,0.203 0.533,0.230 0.517,0.228 0.518,0.215 0.513,0.211 0.512,0.188 0.520,0.155 0.536,0.168",
        "DNK" to
            "0.524,0.155 0.520,0.155 0.518,0.138 0.526,0.124 0.524,0.155",
        "DOM" to
            "0.282,0.453 0.282,0.441 0.292,0.449 0.282,0.453",
        "DZA" to
            "0.469,0.389 0.469,0.379 0.491,0.354 0.491,0.328 0.519,0.319 0.517,0.341 0.524,0.375 0.522,0.398 0.530,0.416 0.504,0.446 0.469,0.389",
        "ECU" to
            "0.271,0.568 0.262,0.596 0.256,0.595 0.257,0.562 0.271,0.568",
        "EGY" to
            "0.604,0.426 0.569,0.426 0.568,0.363 0.596,0.362 0.596,0.386 0.590,0.373 0.604,0.426",
        "ERI" to
            "0.602,0.476 0.608,0.453 0.622,0.487 0.602,0.476",
        "ESP" to
            "0.472,0.318 0.476,0.283 0.467,0.269 0.471,0.263 0.503,0.274 0.488,0.321 0.472,0.318",
        "EST" to
            "0.577,0.103 0.575,0.127 0.564,0.113 0.577,0.103",
        "ETH" to
            "0.636,0.517 0.612,0.546 0.592,0.518 0.607,0.473 0.618,0.482 0.624,0.510 0.636,0.517",
        "FIN" to
            "0.579,0.000 0.583,0.000 0.587,0.066 0.578,0.090 0.562,0.098 0.557,0.063 0.569,0.021 0.564,0.000 0.556,0.000 0.579,0.000",
        "FRA" to
            "0.341,0.541 0.333,0.553 0.335,0.531 0.341,0.541;0.513,0.211 0.518,0.215 0.512,0.237 0.517,0.264 0.500,0.275 0.489,0.266 0.491,0.243 0.481,0.219 0.490,0.219 0.489,0.208 0.502,0.195 0.513,0.211",
        "GAB" to
            "0.528,0.553 0.537,0.560 0.537,0.576 0.527,0.592 0.521,0.574 0.528,0.553",
        "GBR" to
            "0.485,0.172 0.476,0.135 0.480,0.113 0.486,0.113 0.482,0.126 0.489,0.124 0.485,0.144 0.499,0.179 0.499,0.193 0.477,0.204 0.484,0.192 0.479,0.186 0.481,0.171 0.485,0.172",
        "GEO" to
            "0.613,0.266 0.633,0.285 0.618,0.282 0.613,0.266",
        "GHA" to
            "0.495,0.498 0.498,0.530 0.486,0.536 0.486,0.498 0.495,0.498",
        "GIN" to
            "0.454,0.488 0.467,0.490 0.471,0.513 0.467,0.521 0.462,0.504 0.455,0.511 0.450,0.498 0.454,0.488",
        "GRC" to
            "0.562,0.283 0.573,0.282 0.562,0.292 0.566,0.313 0.561,0.323 0.554,0.298 0.562,0.283",
        "GRL" to
            "0.356,0.000 0.458,0.000 0.393,0.003 0.377,0.022 0.366,0.095 0.362,0.096 0.352,0.086 0.342,0.048 0.335,0.000 0.344,0.000 0.277,0.000 0.363,0.000 0.356,0.000",
        "GTM" to
            "0.221,0.475 0.226,0.466 0.225,0.454 0.233,0.468 0.228,0.481 0.221,0.475",
        "GUY" to
            "0.327,0.555 0.318,0.556 0.313,0.530 0.315,0.519 0.325,0.530 0.323,0.542 0.327,0.555",
        "HND" to
            "0.248,0.473 0.236,0.485 0.230,0.476 0.234,0.467 0.248,0.473",
        "HRV" to
            "0.544,0.239 0.552,0.250 0.541,0.254 0.549,0.274 0.535,0.251 0.544,0.239",
        "HTI" to
            "0.282,0.442 0.282,0.453 0.274,0.451 0.282,0.442",
        "HUN" to
            "0.560,0.221 0.557,0.240 0.542,0.236 0.545,0.224 0.560,0.221",
        "IDN" to
            "0.912,0.583 0.912,0.624 0.902,0.620 0.903,0.601 0.888,0.593 0.886,0.585 0.891,0.581 0.881,0.573 0.891,0.572 0.896,0.588 0.902,0.578 0.912,0.583;0.844,0.541 0.847,0.562 0.839,0.592 0.821,0.586 0.818,0.570 0.819,0.555 0.832,0.560 0.838,0.540 0.844,0.541;0.859,0.562 0.866,0.558 0.850,0.570 0.860,0.571 0.854,0.579 0.859,0.601 0.853,0.584 0.848,0.601 0.850,0.564 0.859,0.562;0.816,0.607 0.837,0.620 0.807,0.610 0.816,0.607;0.804,0.574 0.809,0.586 0.808,0.604 0.798,0.594 0.777,0.533 0.804,0.574",
        "IND" to
            "0.783,0.383 0.769,0.426 0.765,0.416 0.768,0.406 0.757,0.396 0.758,0.429 0.732,0.467 0.731,0.502 0.724,0.517 0.710,0.431 0.703,0.434 0.696,0.415 0.705,0.410 0.700,0.393 0.717,0.354 0.713,0.339 0.725,0.330 0.728,0.360 0.735,0.370 0.732,0.379 0.741,0.390 0.767,0.393 0.779,0.375 0.783,0.383",
        "IRL" to
            "0.476,0.167 0.474,0.183 0.465,0.188 0.466,0.167 0.472,0.153 0.476,0.167",
        "IRN" to
            "0.638,0.371 0.629,0.342 0.631,0.329 0.625,0.299 0.637,0.298 0.645,0.319 0.662,0.310 0.676,0.322 0.675,0.372 0.682,0.394 0.677,0.405 0.665,0.401 0.638,0.371",
        "IRQ" to
            "0.611,0.355 0.617,0.323 0.627,0.317 0.638,0.371 0.627,0.377 0.611,0.355",
        "ISL" to
            "0.452,0.007 0.454,0.027 0.439,0.050 0.427,0.044 0.430,0.037 0.424,0.030 0.429,0.023 0.422,0.020 0.429,0.007 0.434,0.018 0.452,0.007",
        "ITA" to
            "0.525,0.235 0.535,0.239 0.532,0.260 0.549,0.296 0.544,0.291 0.541,0.311 0.540,0.294 0.525,0.262 0.517,0.264 0.515,0.243 0.525,0.235",
        "JOR" to
            "0.600,0.353 0.609,0.346 0.611,0.355 0.601,0.377 0.598,0.374 0.600,0.353",
        "JPN" to
            "0.915,0.301 0.910,0.333 0.883,0.342 0.886,0.348 0.880,0.361 0.878,0.347 0.908,0.309 0.910,0.285 0.915,0.301;0.923,0.261 0.926,0.267 0.909,0.282 0.915,0.247 0.923,0.261",
        "KAZ" to
            "0.753,0.213 0.731,0.253 0.732,0.275 0.714,0.267 0.698,0.289 0.687,0.263 0.678,0.265 0.668,0.247 0.660,0.252 0.660,0.284 0.650,0.280 0.644,0.256 0.652,0.250 0.652,0.236 0.640,0.240 0.632,0.221 0.635,0.201 0.638,0.207 0.645,0.189 0.676,0.198 0.672,0.186 0.677,0.165 0.699,0.150 0.712,0.171 0.722,0.160 0.732,0.197 0.742,0.195 0.753,0.213",
        "KEN" to
            "0.611,0.596 0.595,0.573 0.599,0.533 0.618,0.543 0.618,0.578 0.611,0.596",
        "KGZ" to
            "0.705,0.276 0.714,0.267 0.732,0.275 0.713,0.299 0.700,0.298 0.711,0.287 0.705,0.276",
        "KHM" to
            "0.798,0.491 0.800,0.478 0.813,0.482 0.809,0.498 0.798,0.491",
        "KOR" to
            "0.868,0.313 0.875,0.306 0.878,0.329 0.869,0.338 0.868,0.313",
        "LAO" to
            "0.813,0.478 0.806,0.477 0.802,0.451 0.794,0.456 0.791,0.437 0.797,0.423 0.804,0.435 0.802,0.445 0.813,0.478",
        "LBR" to
            "0.469,0.519 0.472,0.540 0.461,0.525 0.469,0.519",
        "LBY" to
            "0.569,0.426 0.565,0.443 0.525,0.410 0.523,0.369 0.529,0.348 0.551,0.369 0.556,0.351 0.568,0.357 0.569,0.426",
        "LKA" to
            "0.737,0.520 0.733,0.530 0.732,0.506 0.737,0.520",
        "LTU" to
            "0.573,0.148 0.564,0.166 0.557,0.143 0.573,0.148",
        "LVA" to
            "0.575,0.127 0.578,0.142 0.573,0.148 0.557,0.143 0.561,0.124 0.575,0.127",
        "MAR" to
            "0.488,0.333 0.491,0.354 0.469,0.379 0.451,0.430 0.444,0.430 0.477,0.328 0.488,0.333",
        "MDA" to
            "0.573,0.223 0.583,0.239 0.578,0.248 0.573,0.223",
        "MDG" to
            "0.641,0.646 0.644,0.663 0.634,0.728 0.625,0.728 0.626,0.670 0.641,0.646",
        "MEX" to
            "0.147,0.352 0.179,0.358 0.187,0.376 0.195,0.375 0.207,0.400 0.205,0.427 0.215,0.452 0.229,0.431 0.237,0.434 0.234,0.451 0.225,0.454 0.226,0.466 0.221,0.475 0.196,0.458 0.183,0.444 0.180,0.421 0.154,0.358 0.170,0.418 0.162,0.408 0.147,0.352",
        "MLI" to
            "0.460,0.489 0.460,0.470 0.478,0.469 0.475,0.406 0.507,0.445 0.505,0.469 0.483,0.482 0.478,0.502 0.460,0.489",
        "MMR" to
            "0.791,0.437 0.783,0.450 0.790,0.492 0.786,0.505 0.782,0.460 0.774,0.466 0.768,0.430 0.785,0.383 0.784,0.414 0.794,0.427 0.791,0.437",
        "MNG" to
            "0.754,0.213 0.768,0.198 0.783,0.209 0.787,0.186 0.816,0.213 0.840,0.207 0.837,0.227 0.849,0.234 0.805,0.281 0.780,0.272 0.764,0.250 0.764,0.235 0.754,0.213",
        "MOZ" to
            "0.597,0.640 0.614,0.632 0.615,0.660 0.598,0.693 0.600,0.722 0.590,0.740 0.587,0.710 0.592,0.673 0.584,0.661 0.593,0.655 0.598,0.674 0.597,0.640",
        "MRT" to
            "0.444,0.433 0.456,0.431 0.459,0.400 0.469,0.400 0.469,0.389 0.480,0.406 0.475,0.406 0.478,0.469 0.446,0.465 0.444,0.433",
        "MWI" to
            "0.592,0.625 0.600,0.659 0.598,0.674 0.591,0.654 0.592,0.625",
        "MYS" to
            "0.791,0.527 0.800,0.533 0.803,0.559 0.795,0.550 0.791,0.527;0.844,0.541 0.838,0.540 0.832,0.560 0.819,0.555 0.836,0.540 0.840,0.524 0.848,0.533 0.844,0.541",
        "NAM" to
            "0.553,0.727 0.553,0.753 0.543,0.753 0.529,0.677 0.569,0.679 0.556,0.683 0.553,0.727",
        "NER" to
            "0.538,0.421 0.542,0.437 0.537,0.489 0.511,0.480 0.505,0.494 0.496,0.479 0.505,0.469 0.507,0.445 0.530,0.416 0.538,0.421",
        "NGA" to
            "0.502,0.528 0.507,0.481 0.538,0.491 0.520,0.537 0.502,0.528",
        "NIC" to
            "0.247,0.499 0.235,0.486 0.248,0.473 0.247,0.499",
        "NLD" to
            "0.515,0.171 0.513,0.198 0.504,0.193 0.515,0.171",
        "NOR" to
            "0.587,0.000 0.542,0.000 0.530,0.055 0.532,0.080 0.527,0.110 0.511,0.114 0.509,0.071 0.538,0.000 0.587,0.000",
        "NPL" to
            "0.756,0.386 0.753,0.396 0.732,0.379 0.736,0.368 0.756,0.386",
        "NZL" to
            "0.997,0.870 1.000,0.844 1.000,0.890 0.988,0.893 0.997,0.870",
        "OMN" to
            "0.658,0.422 0.662,0.407 0.672,0.424 0.665,0.447 0.652,0.462 0.649,0.446 0.657,0.440 0.658,0.422",
        "PAK" to
            "0.725,0.330 0.713,0.339 0.717,0.354 0.700,0.393 0.705,0.410 0.677,0.405 0.682,0.394 0.675,0.372 0.691,0.372 0.707,0.322 0.717,0.317 0.725,0.330",
        "PAN" to
            "0.265,0.513 0.264,0.522 0.260,0.511 0.256,0.522 0.249,0.516 0.265,0.513",
        "PER" to
            "0.287,0.594 0.275,0.614 0.291,0.646 0.286,0.684 0.269,0.660 0.253,0.597 0.262,0.596 0.272,0.568 0.287,0.594",
        "PHL" to
            "0.869,0.515 0.866,0.532 0.861,0.518 0.856,0.522 0.866,0.506 0.869,0.515;0.857,0.452 0.855,0.477 0.862,0.488 0.850,0.470 0.852,0.450 0.857,0.452",
        "PNG" to
            "0.912,0.583 0.932,0.605 0.941,0.634 0.923,0.615 0.912,0.624 0.912,0.583",
        "POL" to
            "0.564,0.166 0.562,0.215 0.542,0.202 0.536,0.176 0.547,0.156 0.564,0.166",
        "PRK" to
            "0.882,0.275 0.872,0.296 0.874,0.308 0.864,0.310 0.865,0.290 0.882,0.275",
        "PRT" to
            "0.468,0.279 0.476,0.283 0.471,0.320 0.466,0.305 0.468,0.279",
        "PRY" to
            "0.322,0.696 0.323,0.709 0.334,0.722 0.329,0.745 0.321,0.743 0.323,0.729 0.309,0.710 0.311,0.692 0.322,0.696",
        "ROU" to
            "0.578,0.248 0.582,0.250 0.579,0.263 0.562,0.262 0.554,0.242 0.563,0.224 0.573,0.223 0.578,0.248",
        "RUS" to
            "0.640,0.240 0.633,0.256 0.636,0.285 0.603,0.250 0.613,0.210 0.589,0.185 0.587,0.175 0.591,0.172 0.586,0.149 0.575,0.127 0.581,0.096 0.578,0.090 0.588,0.059 0.583,0.049 0.583,0.000 0.579,0.000 0.616,0.000 0.608,0.014 0.593,0.004 0.598,0.037 0.604,0.045 0.605,0.027 0.614,0.032 0.612,0.021 0.619,0.006 0.625,0.013 0.623,0.000 0.713,0.000 0.706,0.009 0.709,0.011 0.717,0.000 0.711,0.000 1.000,0.000 0.999,0.098 0.995,0.089 0.979,0.098 0.974,0.118 0.978,0.125 0.975,0.156 0.959,0.196 0.956,0.135 0.982,0.063 0.969,0.090 0.966,0.074 0.959,0.078 0.951,0.099 0.954,0.107 0.916,0.108 0.895,0.158 0.909,0.163 0.913,0.184 0.909,0.221 0.890,0.271 0.882,0.276 0.883,0.252 0.889,0.251 0.895,0.220 0.883,0.227 0.861,0.171 0.851,0.178 0.844,0.211 0.816,0.213 0.787,0.186 0.783,0.209 0.768,0.198 0.753,0.213 0.742,0.195 0.732,0.197 0.722,0.160 0.712,0.171 0.699,0.150 0.677,0.165 0.672,0.186 0.676,0.198 0.645,0.189 0.638,0.207 0.635,0.201 0.632,0.221 0.640,0.240;0.918,0.168 0.923,0.216 0.919,0.213 0.920,0.242 0.915,0.244 0.914,0.173 0.918,0.168;0.594,0.243 0.603,0.248 0.595,0.258 0.591,0.249 0.594,0.243",
        "SAU" to
            "0.598,0.375 0.614,0.357 0.638,0.381 0.649,0.420 0.659,0.426 0.657,0.440 0.621,0.464 0.598,0.375",
        "SDN" to
            "0.567,0.516 0.559,0.488 0.569,0.426 0.604,0.426 0.608,0.453 0.595,0.513 0.591,0.490 0.587,0.506 0.569,0.503 0.567,0.516",
        "SDS" to
            "0.586,0.545 0.565,0.513 0.571,0.502 0.587,0.506 0.593,0.491 0.592,0.518 0.599,0.533 0.586,0.545",
        "SEN" to
            "0.445,0.482 0.442,0.474 0.451,0.462 0.461,0.487 0.445,0.482",
        "SLE" to
            "0.455,0.511 0.462,0.504 0.464,0.515 0.461,0.525 0.455,0.511",
        "SOM" to
            "0.618,0.578 0.616,0.550 0.646,0.492 0.638,0.534 0.618,0.578",
        "SRB" to
            "0.550,0.244 0.562,0.256 0.561,0.274 0.551,0.265 0.550,0.244",
        "SUR" to
            "0.333,0.553 0.327,0.555 0.323,0.537 0.335,0.531 0.333,0.553",
        "SWE" to
            "0.527,0.110 0.532,0.080 0.530,0.055 0.542,0.000 0.564,0.000 0.565,0.014 0.547,0.061 0.545,0.079 0.550,0.095 0.542,0.142 0.533,0.151 0.527,0.110",
        "SYR" to
            "0.600,0.351 0.603,0.320 0.620,0.317 0.616,0.338 0.600,0.351",
        "TCD" to
            "0.565,0.443 0.565,0.469 0.559,0.488 0.562,0.497 0.540,0.521 0.535,0.477 0.542,0.437 0.538,0.421 0.565,0.443",
        "THA" to
            "0.806,0.477 0.800,0.478 0.798,0.491 0.791,0.483 0.788,0.509 0.797,0.528 0.794,0.532 0.785,0.515 0.790,0.492 0.783,0.450 0.791,0.437 0.794,0.456 0.805,0.457 0.806,0.477",
        "TJK" to
            "0.695,0.317 0.695,0.298 0.704,0.287 0.700,0.298 0.713,0.299 0.717,0.315 0.707,0.320 0.704,0.307 0.695,0.317",
        "TKM" to
            "0.650,0.280 0.664,0.284 0.668,0.272 0.692,0.316 0.679,0.332 0.664,0.310 0.654,0.317 0.651,0.294 0.657,0.287 0.650,0.280",
        "TUN" to
            "0.523,0.369 0.517,0.341 0.523,0.316 0.527,0.318 0.525,0.339 0.529,0.348 0.523,0.369",
        "TUR" to
            "0.627,0.317 0.582,0.325 0.576,0.321 0.572,0.299 0.594,0.278 0.621,0.281 0.627,0.297 0.627,0.317;0.572,0.279 0.580,0.284 0.573,0.293 0.572,0.279",
        "TZA" to
            "0.595,0.573 0.611,0.596 0.614,0.632 0.597,0.640 0.586,0.619 0.581,0.595 0.585,0.574 0.595,0.573",
        "UGA" to
            "0.595,0.573 0.582,0.576 0.586,0.545 0.595,0.541 0.598,0.555 0.595,0.573",
        "UKR" to
            "0.589,0.185 0.613,0.210 0.612,0.226 0.598,0.246 0.588,0.237 0.579,0.249 0.583,0.239 0.579,0.224 0.560,0.221 0.564,0.190 0.589,0.185",
        "URY" to
            "0.324,0.765 0.335,0.778 0.335,0.796 0.321,0.792 0.324,0.765",
        "USA" to
            "0.131,0.216 0.214,0.212 0.233,0.222 0.250,0.249 0.250,0.281 0.283,0.252 0.289,0.230 0.296,0.254 0.287,0.264 0.287,0.281 0.271,0.299 0.270,0.317 0.268,0.301 0.270,0.330 0.254,0.360 0.256,0.405 0.246,0.371 0.239,0.368 0.214,0.375 0.206,0.400 0.179,0.358 0.147,0.352 0.137,0.337 0.126,0.292 0.125,0.223 0.131,0.233 0.131,0.216;0.041,0.121 0.044,0.125 0.038,0.135 0.036,0.127 0.041,0.121;0.077,0.000 0.077,0.093 0.087,0.110 0.093,0.099 0.109,0.145 0.108,0.157 0.097,0.119 0.072,0.095 0.059,0.085 0.045,0.107 0.048,0.080 0.025,0.144 0.006,0.161 0.024,0.132 0.029,0.110 0.015,0.113 0.013,0.097 0.005,0.090 0.003,0.070 0.018,0.046 0.018,0.032 0.001,0.033 0.001,0.012 0.015,0.012 0.000,0.000 0.077,0.000",
        "UZB" to
            "0.660,0.284 0.660,0.252 0.668,0.247 0.678,0.265 0.687,0.263 0.692,0.285 0.705,0.276 0.711,0.287 0.700,0.289 0.694,0.301 0.695,0.317 0.668,0.272 0.660,0.284",
        "VEN" to
            "0.315,0.535 0.302,0.542 0.307,0.553 0.298,0.563 0.294,0.550 0.295,0.529 0.281,0.523 0.277,0.510 0.283,0.493 0.283,0.510 0.287,0.491 0.311,0.500 0.317,0.515 0.315,0.535",
        "VNM" to
            "0.804,0.501 0.813,0.490 0.813,0.471 0.797,0.423 0.807,0.417 0.815,0.429 0.808,0.446 0.818,0.483 0.806,0.513 0.804,0.501",
        "YEM" to
            "0.649,0.446 0.649,0.469 0.623,0.484 0.623,0.456 0.649,0.446",
        "ZAF" to
            "0.543,0.753 0.553,0.753 0.553,0.727 0.559,0.740 0.582,0.709 0.589,0.724 0.585,0.740 0.592,0.740 0.578,0.784 0.554,0.799 0.549,0.794 0.543,0.753",
        "ZMB" to
            "0.586,0.619 0.593,0.628 0.593,0.655 0.575,0.681 0.559,0.669 0.559,0.648 0.566,0.648 0.565,0.636 0.582,0.651 0.579,0.625 0.586,0.619",
        "ZWE" to
            "0.587,0.710 0.578,0.705 0.569,0.680 0.584,0.665 0.592,0.673 0.587,0.710",
    )

    private val cache = HashMap<String, List<List<Offset>>>()

    /** Filled rings (normalised 0..1) for a country, or empty if none. */
    fun rings(code: String): List<List<Offset>> =
        cache.getOrPut(code) {
            val p = packed[code] ?: return@getOrPut emptyList()
            p.split(';').map { ring ->
                ring.split(' ').map { pt ->
                    val c = pt.split(',')
                    Offset(c[0].toFloat(), c[1].toFloat())
                }
            }
        }
}
