#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generate Progression.kt: the recognition-wave map (city -> wave) + per-rank difficulty tables.
import re, json, io

def parse(p): return re.findall(r'CityInfo\("([^"]+)",\s*"([^"]+)"', open(p,encoding='utf-8').read())
BASE="/home/deniswsrosa/Documents/projects/WhereIS/android/app/src/main/java/com/acme/clara/data/"
exp=parse(BASE+"Expansion.kt")
new=json.load(open('country_strategy.json'))
EXP_TIER={ "Amsterdam":1,"Berlin":1,"Dubai":1,"Cape Town":1,"Copenhagen":1,"Edinburgh":1,"Mount Everest":1,"Grand Canyon":1,"Hong Kong":1,"Jerusalem":1,"Las Vegas":1,"Los Angeles":1,"Prague":1,"San Francisco":1,"Santorini":1,"Stonehenge":1,"Venice":1,"Vienna":1,"Washington DC":1,"Chichen Itza":1,"Easter Island":1,"Iguazu Falls":1,"Vatican City":1,"Pisa":1,"Pompeii":1,"Mount Rushmore":1,"Neuschwanstein":1,"Bali":1,"Cambodia":1,"Ha Long Bay":1,"Marrakech":1,"Lisbon":1,"Krakow":1,"Dubrovnik":1,"Ireland":1,"Jordan":1,"Saint Petersburg":1,"Monaco":1,"Kuala Lumpur":1,"Honolulu":1,"Abu Simbel":2,"Cappadocia":2,"Casablanca":2,"Cologne":2,"Greenland":2,"Mongolia":2,"Myanmar":2,"Northern Ireland":2,"Scottish Highlands":2,"Valencia":2,"Mauritius":2,"Palau":2,"Samarkand":2,"Salar de Uyuni":2,"Svalbard":2,"Kenya":2,"Mont Saint-Michel":2,"Bhutan":2,"Taipei":2,"Toronto":2,"Seattle":2,"Philippines":2,"Gujarat":3,"Novosibirsk":3,"Turkmenistan":3,"Tuvalu":3,"Maranhao":3,"Antarctica":3 }
def cont(r):
    r=r.lower()
    if 'middle east' in r or r=='asia': return 'Asia'
    if 'america' in r: return 'Americas'
    if 'oceania' in r: return 'Oceania'
    if 'antarctic' in r: return 'Antarctica'
    if 'africa' in r: return 'Africa'
    if 'europe' in r: return 'Europe'
    return r.title()
def band(t): return "core" if t in (1,2) else "deep"
WAVES=[({"Europe"},"core"),({"Americas"},"core"),({"Asia"},"core"),({"Africa"},"core"),({"Oceania"},"core"),
 ({"Europe"},"deep"),({"Americas"},"deep"),({"Asia"},"deep"),({"Africa"},"deep"),({"Oceania","Antarctica"},"deep")]
def wave_of(continent,tier):
    for i,(cs,bd) in enumerate(WAVES):
        if continent in cs and band(tier)==bd: return i
    return -1

wave={}
for n,r in exp: wave[n]=wave_of(cont(r),EXP_TIER[n])
for c in new:   wave[c['name']]=wave_of(c['continent'],c['tier'])
assert all(v>=0 for v in wave.values()), [k for k,v in wave.items() if v<0]
print("paid cities mapped:",len(wave))

# difficulty tables, 15 ranks: 5 free (Rookie..Ace) + 10 International grades (waves 0-9)
HOPS =[5,6,7,8,9,  9,9,10,10,10,11,11,11,12,12]
NEWPC=[1,1,1,1,1,  1,1,2,2,2, 3,3,3,3,3]
SLACK=[30,28,26,25,24, 24,23,22,20,19, 18,17,16,15,15]  # clock-hours of spare time (buffer)

def kstr(s): return s.replace('\\','\\\\').replace('$','\\$').replace('"','\\"')
items=", ".join(f'"{kstr(k)}" to {v}' for k,v in sorted(wave.items(), key=lambda kv:(kv[1],kv[0])))

L=[]
L.append("// AUTO-GENERATED by scripts/gen_progression.py — recognition-wave map + difficulty tables.")
L.append("package com.acme.clara.data")
L.append("")
L.append("import kotlin.math.roundToInt")
L.append("")
L.append("/**")
L.append(" * Level rules (see docs/05-game-design-and-progression.md).")
L.append(" *")
L.append(" * Ranks 0..4 are the free career (Rookie..Ace Detective, originals only). Ranks 5..14 are the")
L.append(" * paid \"International\" grades; each unlocks one recognition [wave] of countries, famous first.")
L.append(" * Difficulty per rank: [hops] route length, [newPerCase] first-sightings cap, and [slackHours]")
L.append(" * spare time above the route's travel need (the case deadline = travel estimate + slack).")
L.append(" */")
L.append("object Progression {")
L.append("    const val FREE_RANKS = 5                 // rankIndex 0..4 = free career")
L.append("    val LAST_RANK = 14                       // 5 free + 10 International grades")
L.append("")
L.append("    private val HOPS  = intArrayOf(%s)" % ", ".join(map(str,HOPS)))
L.append("    private val NEWPC = intArrayOf(%s)" % ", ".join(map(str,NEWPC)))
L.append("    private val SLACK = intArrayOf(%s)" % ", ".join(map(str,SLACK)))
L.append("    private fun clampRank(r: Int) = r.coerceIn(0, LAST_RANK)")
L.append("")
L.append("    /** Route length (number of destination hops) for a rank. */")
L.append("    fun hops(rank: Int) = HOPS[clampRank(rank)]")
L.append("    /** Max brand-new (never-seen) countries introduced per case at a rank. */")
L.append("    fun newPerCase(rank: Int) = NEWPC[clampRank(rank)]")
L.append("    /** Spare hours above the route's travel need (the difficulty knob on the clock). */")
L.append("    fun slackHours(rank: Int) = SLACK[clampRank(rank)]")
L.append("")
L.append("    /** Called only for an entitled career: Wave 1 opens at purchase, before the first paid rank. */")
L.append("    fun unlockedMaxWave(rank: Int): Int = (rank - FREE_RANKS + 1).coerceIn(0, 9)")
L.append("")
L.append("    /** city -> its recognition wave (0 = most famous .. 9 = most obscure). Free 30 are absent. */")
L.append("    val wave: Map<String, Int> = mapOf(%s)" % items)
L.append("")
L.append("    /** Paid cities whose wave is unlocked at this rank (empty during the free career). */")
L.append("    fun citiesUpToWave(maxWave: Int): List<String> =")
L.append("        if (maxWave < 0) emptyList() else wave.filterValues { it <= maxWave }.keys.toList()")
L.append("")
L.append("    /**")
L.append("     * The case deadline in clock-hours: the route's travel need (real flight hours inflated")
L.append("     * ~1.8x for the overnight rests perfect play still incurs, floored per hop) plus this")
L.append("     * rank's slack. Always covers a clean run of the route; slack is the margin for mistakes.")
L.append("     */")
L.append("    fun caseDeadlineHours(rank: Int, routeFlightHours: Int, hops: Int): Int {")
L.append("        val travel = (routeFlightHours * 1.8).roundToInt().coerceAtLeast(hops * 7)")
L.append("        return travel + slackHours(rank)")
L.append("    }")
L.append("}")
L.append("")

out="\n".join(L)
io.open(BASE+"Progression.kt","w",encoding="utf-8").write(out)
print("wrote Progression.kt:", len(out), "bytes")
from collections import Counter
print("wave sizes:", dict(sorted(Counter(wave.values()).items())))
