#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generate Expansion2.kt (the 133 new-country destinations) from the reviewed card content.
import json, re, io

cards=json.load(open('all_cards_133.json'))
strat={c['name']:c for c in json.load(open('country_strategy.json'))}

# landmark phrases (short) reused from the postcard scenes; exec only the SCENE dict (no side effects)
src=io.open('postcard_prompts.py',encoding='utf-8').read()
ns={}; exec(src[:src.index('SLUG_OVERRIDE')], ns)
SCENE=ns.get('SCENE',{})

def kstr(s):
    return (s or "").replace('\\','\\\\').replace('$','\\$').replace('"','\\"')
def phonetic(greet):
    if not greet: return None
    m=re.search(r'\(([^)]+)\)', greet)
    return m.group(1).strip() if m else None
def landmark(name):
    sc=SCENE.get(name)
    if sc:
        return re.sub(r'^(the |a |an )','',sc.split(',')[0].strip(), flags=re.I)
    return "its famous sights"

order={'Africa':0,'Asia':1,'Europe':2,'Americas':3,'Oceania':4}
rows=sorted(cards, key=lambda c:(order.get(strat[c['name']]['continent'],9), c['name']))

L=[]
L.append("// AUTO-GENERATED by scripts/gen_expansion2.py from the reviewed welcome-card set")
L.append("// (welcome_cards_state.md). Clue text is hand-authored & human-reviewed. DO NOT EDIT BY HAND.")
L.append("package com.acme.clara.data")
L.append("")
L.append("/**")
L.append(" * Second paid-tier expansion: 133 new country destinations (nearly every remaining nation).")
L.append(" * Merged into the active pool by recognition wave (see [Progression]); each ships a")
L.append(" * `country_<slug>` briefing postcard. Clues are the forward-looking, subject-less witness")
L.append(" * leads (the game prepends the suspect pronoun + a lead-in, as with [Expansion]).")
L.append(" * Map positions/flight coords are not yet supplied — these default to a neutral hop cost.")
L.append(" */")
L.append("object Expansion2 {")
L.append("    val cities: List<CityInfo> = listOf(")
for c in rows:
    st=strat[c['name']]
    draw=(st['postcard']['file'] or '').replace('.png','')
    clues=[kstr(h['text']) for h in c['hints']]
    clues_kt=", ".join(f"\"{t}\"" for t in clues)
    greet=phonetic(c.get('greeting',{}).get('text') if c.get('greeting') else None)
    greet_kt = f"\"{kstr(greet)}\"" if greet else "null"
    L.append(f"        CityInfo(\"{kstr(c['name'])}\", \"{kstr(c['region'])}\", \"{kstr(landmark(c['name']))}\",")
    L.append(f"            \"{kstr(c['arrival'])}\", false, \"{draw}\",")
    L.append(f"            clues = listOf({clues_kt}), greeting = {greet_kt}),")
L.append("    )")
L.append("")
L.append("    val byName: Map<String, CityInfo> = cities.associateBy { it.name }")
L.append("    val names: List<String> = cities.map { it.name }")
L.append("}")
L.append("")

out="\n".join(L)
io.open("/home/deniswsrosa/Documents/projects/WhereIS/android/app/src/main/java/com/acme/clara/data/Expansion2.kt","w",encoding="utf-8").write(out)
print("wrote Expansion2.kt:", len(out), "bytes,", len(rows), "cities")
# sanity: any straight double-quote left unescaped inside values? spot a few
print("sample:", rows[0]['name'], "|", landmark(rows[0]['name']), "| greet", phonetic(rows[0].get('greeting',{}).get('text')))
