[sdl]
autolock=false
[dosbox]
machine=vgaonly
captures=/private/tmp/claude-504/-Users-denisrosa-Documents-projects-whereintheworld/71108252-e4c9-4cdb-a513-4565302fd62c/scratchpad/caps
[cpu]
core=normal
cputype=386
cycles=fixed 5000
[sblaster]
sbtype=none
[dos]
xms=true
ems=false
[render]
scaler=none
[autoexec]
mount c /private/tmp/claude-504/-Users-denisrosa-Documents-projects-whereintheworld/71108252-e4c9-4cdb-a513-4565302fd62c/scratchpad/game
c:
LOADFIX -32
CARMEN.EXE
